### ISSUE TITLE
Patrimoine script is broken

### ISSUE THREAD

**Issue by benbel** [TaxIPP-Life/til-france#18]
To be more precise, TIL-Core matching does not or no longer works with the Patrimoine data used by TIL-France.

````
  return func(*args, **kwargs)
Traceback (most recent call last):
  File "til_init.py", line 269, in <module>
    sys.exit(main())
  File "til_init.py", line 263, in main
    exit_value = task()
  File "til_init.py", line 206, in build_patrimoine_data
    patrimoine()
  File "c:\users\b.belrhomari\z\til\til-france\til_france\data\data\Patrimoine.py", line 1008, in test_build
    data.matching_par_enf()
  File "c:\users\b.belrhomari\z\til\til-france\til_france\data\data\Patrimoine.py", line 805, in matching_par_enf
    method='cells'
  File "c:\users\b.belrhomari\z\til\til-core\til_core\data\utils\matching.py", line 202, in evaluate
    assert match.nunique() == len(match)
AssertionError
````

**Comment by benbel** [comment]
Some precisions for @benjello: running Patrimoine.py on Patrimoine data used to work without problem, and the matching part no longer works. Patrimoine data has not changed (I checked with the very same files that used to work), hence the problem is most likely to come from TIL-France.

The only change that to Patrimoine.py was [this commit](https://github.com/TaxIPP-Life/til-france/commit/794b43e240b66d85fbeafd3b5920f5fdb3d74dd4#diff-3049d7c839484f6b43ec4cec4b002c38), which must have broken something.

I will check if using older versions of OSM/TIL-Core/Til-France works, and then we can start working from there.

**Comment by benjello** [comment]
Thanks @benbel . The changes followed warnings/deprecations from pandas.
I will look into that ASAP.

**Comment by benbel** [comment]
Patrimoine.py as of [this commit](https://github.com/TaxIPP-Life/til-france/commit/c362c1594078c0941a556cc36f6ef0b2f38c26f5) ie before the big changes to Patrimoine.py does not work either, though it must have worked at some point. Likely to be caused by a change in one of the dependencies.
